use std::{
    fs,
    path::{Path, PathBuf},
    process::Stdio,
};

use anyhow::{Context, Result, bail};
use boson_orchestration::Project;
use tokio::process::Command;

pub struct DeployArgs {
    pub output: String,
    pub tag: Option<String>,
    pub build: bool,
    pub push: bool,
}

pub async fn run(args: DeployArgs) -> Result<()> {
    let project = Project::discover(None)?;
    let output = if Path::new(&args.output).is_absolute() {
        PathBuf::from(&args.output)
    } else {
        project.root.join(&args.output)
    };
    fs::create_dir_all(&output).with_context(|| format!("create {}", output.display()))?;

    let image_base = args
        .tag
        .unwrap_or_else(|| format!("{}:{}", project.manifest.name, env!("CARGO_PKG_VERSION")));
    let server_image = format!("{image_base}-server");
    let worker_image = format!("{image_base}-worker");
    let migrate_image = format!("{image_base}-migrate");

    let dockerfile = render_dockerfile(&project);
    let dockerignore = "target\n.boson/run\n.boson/logs\n.boson/deploy\ndata\n.git\n";
    let guide = render_guide(&project, &server_image, &worker_image, &migrate_image);

    fs::write(output.join("Dockerfile"), dockerfile)
        .with_context(|| format!("write {}", output.join("Dockerfile").display()))?;
    fs::write(output.join(".dockerignore"), dockerignore)
        .with_context(|| format!("write {}", output.join(".dockerignore").display()))?;
    fs::write(output.join("CLOUD_RUN.md"), guide)
        .with_context(|| format!("write {}", output.join("CLOUD_RUN.md").display()))?;

    println!("wrote packaging files to {}", output.display());
    println!("  Dockerfile");
    println!("  .dockerignore");
    println!("  CLOUD_RUN.md");
    println!();
    println!("Boson packages application binaries only. It never creates");
    println!("databases, buckets, mail providers, registries, or cloud services.");

    if args.build {
        build_images(
            &project.root,
            &output,
            &server_image,
            &worker_image,
            &migrate_image,
        )
        .await?;
    } else {
        println!();
        println!("Build when ready:");
        println!(
            "  docker build -f {}/Dockerfile --target server -t {server_image} {}",
            output.display(),
            project.root.display()
        );
        println!(
            "  docker build -f {}/Dockerfile --target worker -t {worker_image} {}",
            output.display(),
            project.root.display()
        );
        println!(
            "  docker build -f {}/Dockerfile --target migrate -t {migrate_image} {}",
            output.display(),
            project.root.display()
        );
    }

    if args.push {
        push_image(&server_image).await?;
        push_image(&worker_image).await?;
        push_image(&migrate_image).await?;
        println!("pushed images to the registry you configured in the image tags");
    }

    Ok(())
}

fn render_dockerfile(project: &Project) -> String {
    let server = &project.manifest.server_package;
    let worker = &project.manifest.worker_package;
    let migrate = &project.manifest.migrate_package;
    format!(
        r#"# Generated by `boson deploy`. Packaging only — does not provision infrastructure.
FROM rust:1.94-bookworm AS builder
WORKDIR /workspace
COPY . .
RUN cargo build --release -p {server} -p {worker} -p {migrate}

FROM debian:bookworm-slim AS runtime-base
RUN apt-get update \
    && apt-get install -y --no-install-recommends ca-certificates \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY capabilities ./capabilities
COPY .boson/config.yaml ./.boson/config.yaml

FROM runtime-base AS server
COPY --from=builder /workspace/target/release/{server} /usr/local/bin/boson-server
ENV BOSON_CONFIG=./.boson/config.yaml
EXPOSE 8080
ENTRYPOINT ["boson-server"]

FROM runtime-base AS worker
COPY --from=builder /workspace/target/release/{worker} /usr/local/bin/boson-worker
ENV BOSON_CONFIG=./.boson/config.yaml
ENTRYPOINT ["boson-worker"]

FROM runtime-base AS migrate
COPY --from=builder /workspace/target/release/{migrate} /usr/local/bin/boson-migrate
ENV BOSON_CONFIG=./.boson/config.yaml
ENV BOSON__DATABASE__CONNECT_ON_BOOT=true
ENV BOSON__DATABASE__RUN_MIGRATIONS=true
ENTRYPOINT ["boson-migrate"]
"#
    )
}

fn render_guide(
    project: &Project,
    server_image: &str,
    worker_image: &str,
    migrate_image: &str,
) -> String {
    format!(
        r#"# Cloud Run guidance for {}

Boson packages images; you own infrastructure and deployment.

## Required configuration

Inject secrets/env into each service (never bake production secrets into images):

- `BOSON__DATABASE__URL`
- `BOSON__ADMIN__BOOTSTRAP_TOKEN` or issued Admin API keys
- `BOSON__AUTH__JWT_SECRET`
- Optional production adapters: `BOSON__STORAGE__PROVIDER=s3` and SMTP settings

## Suggested units

1. Run `{migrate_image}` once as a Cloud Run Job before rollout.
2. Deploy `{server_image}` as an HTTP Cloud Run service.
   - Health: `/healthz`
   - Readiness: `/readyz`
   - Port: map Cloud Run `PORT` via `BOSON__HTTP__PORT` if needed
3. Deploy `{worker_image}` as a always-on Cloud Run service or equivalent worker host.

Boson does not create Cloud SQL, buckets, SMTP, Artifact Registry repositories,
IAM roles, or Cloud Run services for you.
"#,
        project.manifest.name
    )
}

async fn build_images(
    root: &Path,
    output: &Path,
    server_image: &str,
    worker_image: &str,
    migrate_image: &str,
) -> Result<()> {
    for (target, image) in [
        ("server", server_image),
        ("worker", worker_image),
        ("migrate", migrate_image),
    ] {
        println!("building {image}");
        let status = Command::new("docker")
            .args([
                "build",
                "-f",
                &output.join("Dockerfile").display().to_string(),
                "--target",
                target,
                "-t",
                image,
                &root.display().to_string(),
            ])
            .stdout(Stdio::inherit())
            .stderr(Stdio::inherit())
            .status()
            .await
            .context(
                "Docker is required for `--build` / `--push`\nfix: install Docker or omit --build",
            )?;
        if !status.success() {
            bail!("docker build failed for target {target}");
        }
    }
    Ok(())
}

async fn push_image(image: &str) -> Result<()> {
    println!("pushing {image}");
    let status = Command::new("docker")
        .args(["push", image])
        .stdout(Stdio::inherit())
        .stderr(Stdio::inherit())
        .status()
        .await
        .context("docker push failed to start")?;
    if !status.success() {
        bail!("docker push failed for {image}");
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    #[test]
    fn dockerfile_targets_project_packages() {
        let dir = tempdir().unwrap();
        fs::create_dir_all(dir.path().join(".boson")).unwrap();
        fs::write(
            dir.path().join(".boson/project.toml"),
            r#"
schema_version = 1
name = "demo-app"
package_prefix = "demo_app"
migrate_package = "demo_app_migrate"
server_package = "demo_app_server"
worker_package = "demo_app_worker"
"#,
        )
        .unwrap();
        fs::write(
            dir.path().join(".boson/config.yaml"),
            "app:\n  name: demo-app\n",
        )
        .unwrap();
        let project = Project::discover(Some(dir.path())).unwrap();
        let dockerfile = render_dockerfile(&project);
        assert!(dockerfile.contains("-p demo_app_server"));
        assert!(dockerfile.contains("AS server"));
        assert!(dockerfile.contains("capabilities"));
        assert!(!dockerfile.contains("docker compose"));
        assert!(!dockerfile.contains("gcloud"));
    }
}
