//! Starter capability generated by `boson create`.

use std::{path::PathBuf, sync::Arc};

use axum::{
    Extension, Json, Router,
    extract::State,
    http::StatusCode,
    middleware,
    response::{IntoResponse, Response},
    routing::{get, post},
};
use boson_sdk::prelude::*;
use serde::{Deserialize, Serialize};
use thiserror::Error;

#[derive(Debug, Clone, Deserialize)]
struct ItemsConfig {
    #[serde(default = "default_max_items")]
    max_items: u32,
}

fn default_max_items() -> u32 {
    100
}

#[derive(Clone)]
struct ItemsState {
    database: Option<Database>,
    auth: IdentityAuth,
    max_items: u32,
}

#[derive(Clone)]
pub struct ItemsCapability {
    state: ItemsState,
}

impl ItemsCapability {
    /// Builds the capability from platform configuration.
    ///
    /// # Errors
    ///
    /// Returns an error when the `items` configuration section is invalid.
    pub fn new(
        database: Option<Database>,
        auth: IdentityAuth,
        config: &PlatformConfig,
    ) -> anyhow::Result<Self> {
        let items = config
            .capability_config::<ItemsConfig>("items")?
            .unwrap_or(ItemsConfig {
                max_items: default_max_items(),
            });
        Ok(Self {
            state: ItemsState {
                database,
                auth,
                max_items: items.max_items,
            },
        })
    }
}

impl Capability for ItemsCapability {
    fn descriptor(&self) -> CapabilityDescriptor {
        CapabilityDescriptor {
            name: "items",
            version: env!("CARGO_PKG_VERSION"),
            dependencies: &["identity"],
        }
    }

    fn scopes(&self) -> &'static [&'static str] {
        &["items:read"]
    }

    fn migrations(&self) -> Option<MigrationSet> {
        Some(MigrationSet {
            owner: "items",
            path: PathBuf::from("capabilities/items/migrations"),
        })
    }

    fn app_router(&self) -> Router {
        Router::new()
            .route("/items", post(create_item).get(list_items))
            .route_layer(middleware::from_fn_with_state(
                self.state.auth.clone(),
                user_auth_middleware,
            ))
            .with_state(self.state.clone())
    }

    fn admin_router(&self) -> Router {
        Router::new()
            .route("/items", get(admin_list_items))
            .with_state(self.state.clone())
    }

    fn event_consumers(&self) -> Vec<Arc<dyn EventConsumer>> {
        vec![Arc::new(ItemCreatedLogger)]
    }

    fn health_checks(&self) -> Vec<Arc<dyn HealthCheck>> {
        vec![Arc::new(ItemsHealth)]
    }
}

#[derive(Debug, Deserialize)]
struct CreateItemRequest {
    title: String,
}

#[derive(Debug, Serialize)]
struct Item {
    id: Uuid,
    owner_id: Uuid,
    title: String,
}

#[derive(Debug, Error)]
enum ItemsError {
    #[error("invalid request: {0}")]
    Invalid(String),
    #[error("items service unavailable: {0}")]
    Unavailable(String),
    #[error("missing required scope `{0}`")]
    Forbidden(&'static str),
}

impl IntoResponse for ItemsError {
    fn into_response(self) -> Response {
        let (status, code) = match &self {
            Self::Invalid(_) => (StatusCode::BAD_REQUEST, "items.invalid"),
            Self::Unavailable(_) => (StatusCode::SERVICE_UNAVAILABLE, "items.unavailable"),
            Self::Forbidden(_) => (StatusCode::FORBIDDEN, "items.forbidden"),
        };
        api_error(status, code, self.to_string())
    }
}

async fn create_item(
    State(state): State<ItemsState>,
    Extension(user): Extension<AuthenticatedUser>,
    Extension(context): Extension<RequestContext>,
    Json(input): Json<CreateItemRequest>,
) -> Result<(StatusCode, Json<Item>), ItemsError> {
    let title = input.title.trim();
    if title.is_empty() {
        return Err(ItemsError::Invalid("title is required".into()));
    }
    let database = state
        .database
        .as_ref()
        .ok_or_else(|| ItemsError::Unavailable("database is not configured".into()))?;
    let count = sqlx::query_scalar::<_, i64>(
        "SELECT COUNT(*) FROM items.items WHERE owner_id = $1 AND deleted_at IS NULL",
    )
    .bind(user.user_id)
    .fetch_one(database.pool())
    .await
    .map_err(|error| ItemsError::Unavailable(error.to_string()))?;
    if count >= i64::from(state.max_items) {
        return Err(ItemsError::Invalid(format!(
            "at most {} items are allowed",
            state.max_items
        )));
    }

    let id = Uuid::now_v7();
    let mut tx = database
        .pool()
        .begin()
        .await
        .map_err(|error| ItemsError::Unavailable(error.to_string()))?;
    sqlx::query("INSERT INTO items.items (id, owner_id, title) VALUES ($1, $2, $3)")
        .bind(id)
        .bind(user.user_id)
        .bind(title)
        .execute(&mut *tx)
        .await
        .map_err(|error| ItemsError::Unavailable(error.to_string()))?;
    publish_in_tx(
        &mut tx,
        &EventEnvelope::new(
            "items.item_created.v1",
            json!({ "id": id, "owner_id": user.user_id, "request_id": context.request_id }),
        ),
    )
    .await
    .map_err(|error| ItemsError::Unavailable(error.to_string()))?;
    tx.commit()
        .await
        .map_err(|error| ItemsError::Unavailable(error.to_string()))?;

    Ok((
        StatusCode::CREATED,
        Json(Item {
            id,
            owner_id: user.user_id,
            title: title.to_owned(),
        }),
    ))
}

async fn list_items(
    State(state): State<ItemsState>,
    Extension(user): Extension<AuthenticatedUser>,
) -> Result<Json<Value>, ItemsError> {
    let database = state
        .database
        .as_ref()
        .ok_or_else(|| ItemsError::Unavailable("database is not configured".into()))?;
    let rows = sqlx::query(
        "SELECT id, owner_id, title FROM items.items
         WHERE owner_id = $1 AND deleted_at IS NULL
         ORDER BY created_at DESC",
    )
    .bind(user.user_id)
    .fetch_all(database.pool())
    .await
    .map_err(|error| ItemsError::Unavailable(error.to_string()))?;
    let items = rows
        .into_iter()
        .map(|row| {
            Ok(Item {
                id: row
                    .try_get("id")
                    .map_err(|e| ItemsError::Unavailable(e.to_string()))?,
                owner_id: row
                    .try_get("owner_id")
                    .map_err(|e| ItemsError::Unavailable(e.to_string()))?,
                title: row
                    .try_get("title")
                    .map_err(|e| ItemsError::Unavailable(e.to_string()))?,
            })
        })
        .collect::<Result<Vec<_>, ItemsError>>()?;
    Ok(Json(json!({ "data": items })))
}

async fn admin_list_items(
    State(state): State<ItemsState>,
    Extension(principal): Extension<AdminPrincipal>,
) -> Result<Json<Value>, ItemsError> {
    require_scope(&principal, "items:read", ItemsError::Forbidden)?;
    let database = state
        .database
        .as_ref()
        .ok_or_else(|| ItemsError::Unavailable("database is not configured".into()))?;
    let rows = sqlx::query(
        "SELECT id, owner_id, title FROM items.items
         WHERE deleted_at IS NULL
         ORDER BY created_at DESC
         LIMIT 100",
    )
    .fetch_all(database.pool())
    .await
    .map_err(|error| ItemsError::Unavailable(error.to_string()))?;
    let items = rows
        .into_iter()
        .map(|row| {
            Ok(json!({
                "id": row.try_get::<Uuid, _>("id").map_err(|e| ItemsError::Unavailable(e.to_string()))?,
                "owner_id": row.try_get::<Uuid, _>("owner_id").map_err(|e| ItemsError::Unavailable(e.to_string()))?,
                "title": row.try_get::<String, _>("title").map_err(|e| ItemsError::Unavailable(e.to_string()))?,
            }))
        })
        .collect::<Result<Vec<_>, ItemsError>>()?;
    Ok(Json(json!({ "data": items })))
}

struct ItemCreatedLogger;

#[async_trait]
impl EventConsumer for ItemCreatedLogger {
    fn name(&self) -> &'static str {
        "items.item_created_logger"
    }

    fn topic(&self) -> &'static str {
        "items.item_created.v1"
    }

    async fn handle(&self, event: &EventEnvelope) -> Result<(), EventError> {
        tracing::info!(topic = %event.topic, id = %event.id, "items capability observed event");
        Ok(())
    }
}

struct ItemsHealth;

#[async_trait]
impl HealthCheck for ItemsHealth {
    async fn check(&self) -> HealthStatus {
        HealthStatus {
            component: "items".into(),
            healthy: true,
            message: None,
            latency_ms: 0,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn descriptor_is_stable() {
        let capability = ItemsCapability {
            state: ItemsState {
                database: None,
                auth: IdentityAuth::new(&AuthConfig {
                    issuer: "test".into(),
                    jwt_secret: "secret".into(),
                    ..AuthConfig::default()
                }),
                max_items: 10,
            },
        };
        assert_eq!(capability.descriptor().name, "items");
        assert_eq!(capability.scopes(), &["items:read"]);
    }
}
