use std::path::PathBuf;

use crate::project::{ProjectManifest, to_pascal_case, to_snake_case};

#[derive(Debug, Clone)]
pub struct TemplateContext {
    pub name: String,
    pub snake: String,
    pub pascal: String,
    pub runtime_dep: String,
    pub sdk_dep: String,
    pub manifest: ProjectManifest,
}

#[derive(Debug, Clone)]
pub enum BosonSource {
    Path(PathBuf),
    Git { url: String, rev: String },
}

impl TemplateContext {
    pub fn new(name: &str, source: BosonSource) -> Self {
        let (runtime_dep, sdk_dep) = match source {
            BosonSource::Path(root) => (
                format!(
                    "version = \"0.1.0\", path = \"{}/crates/runtime\"",
                    root.display()
                ),
                format!(
                    "version = \"0.1.0\", path = \"{}/crates/sdk\"",
                    root.display()
                ),
            ),
            BosonSource::Git { url, rev } => (
                format!(
                    "version = \"0.1.0\", git = \"{url}\", rev = \"{rev}\", package = \"boson-runtime\""
                ),
                format!(
                    "version = \"0.1.0\", git = \"{url}\", rev = \"{rev}\", package = \"boson-sdk\""
                ),
            ),
        };
        Self {
            name: name.to_owned(),
            snake: to_snake_case(name),
            pascal: to_pascal_case(name),
            runtime_dep,
            sdk_dep,
            manifest: ProjectManifest::for_name(name),
        }
    }

    fn render(&self, template: &str) -> String {
        template
            .replace("{{NAME}}", &self.name)
            .replace("{{SNAKE}}", &self.snake)
            .replace("{{PASCAL}}", &self.pascal)
            .replace("{{RUNTIME_DEP}}", &self.runtime_dep)
            .replace("{{SDK_DEP}}", &self.sdk_dep)
            .replace("{{SERVER_PKG}}", &self.manifest.server_package)
            .replace("{{WORKER_PKG}}", &self.manifest.worker_package)
            .replace("{{MIGRATE_PKG}}", &self.manifest.migrate_package)
            .replace("{{CAPABILITY_PKG}}", &format!("{}_items", self.snake))
    }
}

pub struct TemplateFile {
    pub relative_path: &'static str,
    pub contents: String,
}

pub fn render_project(ctx: &TemplateContext) -> Vec<TemplateFile> {
    let files = [
        (".boson/project.toml", PROJECT_TOML),
        ("Cargo.toml", WORKSPACE_TOML),
        ("README.md", README),
        ("rust-toolchain.toml", RUST_TOOLCHAIN),
        (".boson/config.yaml", CONFIG_LOCAL),
        (".gitignore", GITIGNORE),
        ("apps/server/Cargo.toml", SERVER_CARGO),
        ("apps/server/src/main.rs", SERVER_MAIN),
        ("apps/worker/Cargo.toml", WORKER_CARGO),
        ("apps/worker/src/main.rs", WORKER_MAIN),
        ("apps/migrate/Cargo.toml", MIGRATE_CARGO),
        ("apps/migrate/src/main.rs", MIGRATE_MAIN),
        ("capabilities/items/Cargo.toml", ITEMS_CARGO),
        ("capabilities/items/src/lib.rs", ITEMS_LIB),
        (
            "capabilities/items/migrations/20260718210000_items.sql",
            ITEMS_MIGRATION,
        ),
    ];
    files
        .into_iter()
        .map(|(relative_path, template)| TemplateFile {
            relative_path,
            contents: ctx.render(template),
        })
        .collect()
}

const PROJECT_TOML: &str = r#"schema_version = 1
name = "{{NAME}}"
package_prefix = "{{SNAKE}}"
migrate_package = "{{MIGRATE_PKG}}"
server_package = "{{SERVER_PKG}}"
worker_package = "{{WORKER_PKG}}"
"#;

const WORKSPACE_TOML: &str = r#"[workspace]
members = [
    "apps/server",
    "apps/worker",
    "apps/migrate",
    "capabilities/items",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
rust-version = "1.94"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = "warn"
pedantic = "warn"
"#;

const README: &str = r#"# {{NAME}}

Standalone Boson application generated by `boson init`.

## Quick start

```bash
boson start
```

Configure the infrastructure you own in `.boson/config.yaml`, then run
`boson start`. Boson validates configuration, applies pending migrations,
launches the Server and Worker, and streams unified logs. Press Ctrl+C to stop.

Useful commands: `boson status`, `boson logs`, `boson doctor`, `boson stop`.

The starter `items` capability exposes:

- `POST /v1/items` / `GET /v1/items` (authenticated end-user)
- `GET /admin/v1/items` (`items:read` Admin scope)

Edit `capabilities/items` and register additional capabilities from
`apps/server`, `apps/worker`, and `apps/migrate` through `boson_runtime::Builder::extend`.
"#;

const RUST_TOOLCHAIN: &str = r#"[toolchain]
channel = "1.94.0"
components = ["clippy", "rustfmt"]
profile = "minimal"
"#;

const CONFIG_LOCAL: &str = r#"app:
  name: {{NAME}}
  environment: development

http:
  host: 0.0.0.0
  port: 8080

database:
  url: postgres://boson:boson@localhost:5432/boson
  max_connections: 10
  connect_on_boot: true
  run_migrations: true

database_inspection:
  enabled: true

telemetry:
  log_level: info
  json: false

admin:
  bootstrap_token: local-development-token

auth:
  issuer: {{NAME}}
  jwt_secret: local-development-jwt-secret
  access_ttl_seconds: 900
  refresh_ttl_days: 30
  email_verification_ttl_hours: 24
  password_reset_ttl_minutes: 60

storage:
  provider: local
  local_root: data/storage
  public_base_url: ""

queue:
  provider: postgres
  poll_interval_ms: 1000
  batch_size: 25
  visibility_timeout_seconds: 60
  max_attempts: 5

mail:
  provider: local
  from: "Boson <no-reply@localhost>"
  local_root: data/mail
  public_app_url: http://localhost:3000

capabilities:
  items:
    max_items: 100
"#;

const GITIGNORE: &str = r#"/target
/data
.boson/run/
.boson/logs/
.env
.DS_Store
"#;

const SERVER_CARGO: &str = r#"[package]
name = "{{SERVER_PKG}}"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1.0.103"
{{CAPABILITY_PKG}} = { path = "../../capabilities/items" }
boson-runtime = { {{RUNTIME_DEP}} }
tokio = { version = "1.53.0", features = ["full"] }
"#;

const SERVER_MAIN: &str = r#"use std::sync::Arc;

use anyhow::Result;
use {{CAPABILITY_PKG}}::ItemsCapability;

#[tokio::main]
async fn main() -> Result<()> {
    boson_runtime::Builder::from_env()
        .extend(|ctx, registry| {
            registry.register(Arc::new(ItemsCapability::new(
                ctx.database.clone(),
                ctx.identity_auth.clone(),
                &ctx.config,
            )?))?;
            Ok(())
        })
        .run_server()
        .await
}
"#;

const WORKER_CARGO: &str = r#"[package]
name = "{{WORKER_PKG}}"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1.0.103"
{{CAPABILITY_PKG}} = { path = "../../capabilities/items" }
boson-runtime = { {{RUNTIME_DEP}} }
tokio = { version = "1.53.0", features = ["full"] }
"#;

const WORKER_MAIN: &str = r#"use std::sync::Arc;

use anyhow::Result;
use {{CAPABILITY_PKG}}::ItemsCapability;

#[tokio::main]
async fn main() -> Result<()> {
    boson_runtime::Builder::from_env()
        .extend(|ctx, registry| {
            registry.register(Arc::new(ItemsCapability::new(
                ctx.database.clone(),
                ctx.identity_auth.clone(),
                &ctx.config,
            )?))?;
            Ok(())
        })
        .run_worker()
        .await
}
"#;

const MIGRATE_CARGO: &str = r#"[package]
name = "{{MIGRATE_PKG}}"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1.0.103"
{{CAPABILITY_PKG}} = { path = "../../capabilities/items" }
boson-runtime = { {{RUNTIME_DEP}} }
tokio = { version = "1.53.0", features = ["full"] }
"#;

const MIGRATE_MAIN: &str = r#"use std::sync::Arc;

use anyhow::Result;
use {{CAPABILITY_PKG}}::ItemsCapability;

#[tokio::main]
async fn main() -> Result<()> {
    boson_runtime::Builder::from_env()
        .extend(|ctx, registry| {
            registry.register(Arc::new(ItemsCapability::new(
                ctx.database.clone(),
                ctx.identity_auth.clone(),
                &ctx.config,
            )?))?;
            Ok(())
        })
        .migrate()
        .await
}
"#;

const ITEMS_CARGO: &str = r#"[package]
name = "{{CAPABILITY_PKG}}"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1.0.103"
async-trait = "0.1.89"
axum = "0.8.9"
boson-sdk = { {{SDK_DEP}} }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
thiserror = "2.0.18"
tracing = "0.1.44"

[lints]
workspace = true
"#;

const ITEMS_LIB: &str = r#"//! Starter capability generated by `boson init`.

use std::{path::PathBuf, sync::Arc};

use axum::{
    Extension, Json, Router,
    extract::State,
    http::StatusCode,
    middleware,
    response::{IntoResponse, Response},
    routing::{get, post},
};
use boson_sdk::prelude::*;
use serde::{Deserialize, Serialize};
use thiserror::Error;

#[derive(Debug, Clone, Deserialize)]
struct ItemsConfig {
    #[serde(default = "default_max_items")]
    max_items: u32,
}

fn default_max_items() -> u32 {
    100
}

#[derive(Clone)]
struct ItemsState {
    database: Option<Database>,
    auth: IdentityAuth,
    max_items: u32,
}

#[derive(Clone)]
pub struct ItemsCapability {
    state: ItemsState,
}

impl ItemsCapability {
    /// Builds the capability from platform configuration.
    ///
    /// # Errors
    ///
    /// Returns an error when the `items` configuration section is invalid.
    pub fn new(
        database: Option<Database>,
        auth: IdentityAuth,
        config: &PlatformConfig,
    ) -> anyhow::Result<Self> {
        let items = config
            .capability_config::<ItemsConfig>("items")?
            .unwrap_or(ItemsConfig {
                max_items: default_max_items(),
            });
        Ok(Self {
            state: ItemsState {
                database,
                auth,
                max_items: items.max_items,
            },
        })
    }
}

impl Capability for ItemsCapability {
    fn descriptor(&self) -> CapabilityDescriptor {
        CapabilityDescriptor {
            name: "items",
            version: env!("CARGO_PKG_VERSION"),
            dependencies: &["identity"],
        }
    }

    fn scopes(&self) -> &'static [&'static str] {
        &["items:read"]
    }

    fn migrations(&self) -> Option<MigrationSet> {
        Some(MigrationSet {
            owner: "items",
            path: PathBuf::from("capabilities/items/migrations"),
        })
    }

    fn app_router(&self) -> Router {
        Router::new()
            .route("/items", post(create_item).get(list_items))
            .route_layer(middleware::from_fn_with_state(
                self.state.auth.clone(),
                user_auth_middleware,
            ))
            .with_state(self.state.clone())
    }

    fn admin_router(&self) -> Router {
        Router::new()
            .route("/items", get(admin_list_items))
            .with_state(self.state.clone())
    }

    fn event_consumers(&self) -> Vec<Arc<dyn EventConsumer>> {
        vec![Arc::new(ItemCreatedLogger)]
    }

    fn health_checks(&self) -> Vec<Arc<dyn HealthCheck>> {
        vec![Arc::new(ItemsHealth)]
    }
}

#[derive(Debug, Deserialize)]
struct CreateItemRequest {
    title: String,
}

#[derive(Debug, Serialize)]
struct Item {
    id: Uuid,
    owner_id: Uuid,
    title: String,
}

#[derive(Debug, Error)]
enum ItemsError {
    #[error("invalid request: {0}")]
    Invalid(String),
    #[error("items service unavailable: {0}")]
    Unavailable(String),
    #[error("missing required scope `{0}`")]
    Forbidden(&'static str),
}

impl IntoResponse for ItemsError {
    fn into_response(self) -> Response {
        let (status, code) = match &self {
            Self::Invalid(_) => (StatusCode::BAD_REQUEST, "items.invalid"),
            Self::Unavailable(_) => (StatusCode::SERVICE_UNAVAILABLE, "items.unavailable"),
            Self::Forbidden(_) => (StatusCode::FORBIDDEN, "items.forbidden"),
        };
        api_error(status, code, self.to_string())
    }
}

async fn create_item(
    State(state): State<ItemsState>,
    Extension(user): Extension<AuthenticatedUser>,
    Extension(context): Extension<RequestContext>,
    Json(input): Json<CreateItemRequest>,
) -> Result<(StatusCode, Json<Item>), ItemsError> {
    let title = input.title.trim();
    if title.is_empty() {
        return Err(ItemsError::Invalid("title is required".into()));
    }
    let database = state
        .database
        .as_ref()
        .ok_or_else(|| ItemsError::Unavailable("database is not configured".into()))?;
    let count = sqlx::query_scalar::<_, i64>(
        "SELECT COUNT(*) FROM items.items WHERE owner_id = $1 AND deleted_at IS NULL",
    )
    .bind(user.user_id)
    .fetch_one(database.pool())
    .await
    .map_err(|error| ItemsError::Unavailable(error.to_string()))?;
    if count >= i64::from(state.max_items) {
        return Err(ItemsError::Invalid(format!(
            "at most {} items are allowed",
            state.max_items
        )));
    }

    let id = Uuid::now_v7();
    let mut tx = database
        .pool()
        .begin()
        .await
        .map_err(|error| ItemsError::Unavailable(error.to_string()))?;
    sqlx::query("INSERT INTO items.items (id, owner_id, title) VALUES ($1, $2, $3)")
        .bind(id)
        .bind(user.user_id)
        .bind(title)
        .execute(&mut *tx)
        .await
        .map_err(|error| ItemsError::Unavailable(error.to_string()))?;
    publish_in_tx(
        &mut tx,
        &EventEnvelope::new(
            "items.item_created.v1",
            json!({ "id": id, "owner_id": user.user_id, "request_id": context.request_id }),
        ),
    )
    .await
    .map_err(|error| ItemsError::Unavailable(error.to_string()))?;
    tx.commit()
        .await
        .map_err(|error| ItemsError::Unavailable(error.to_string()))?;

    Ok((
        StatusCode::CREATED,
        Json(Item {
            id,
            owner_id: user.user_id,
            title: title.to_owned(),
        }),
    ))
}

async fn list_items(
    State(state): State<ItemsState>,
    Extension(user): Extension<AuthenticatedUser>,
) -> Result<Json<Value>, ItemsError> {
    let database = state
        .database
        .as_ref()
        .ok_or_else(|| ItemsError::Unavailable("database is not configured".into()))?;
    let rows = sqlx::query(
        "SELECT id, owner_id, title FROM items.items
         WHERE owner_id = $1 AND deleted_at IS NULL
         ORDER BY created_at DESC",
    )
    .bind(user.user_id)
    .fetch_all(database.pool())
    .await
    .map_err(|error| ItemsError::Unavailable(error.to_string()))?;
    let items = rows
        .into_iter()
        .map(|row| {
            Ok(Item {
                id: row
                    .try_get("id")
                    .map_err(|e| ItemsError::Unavailable(e.to_string()))?,
                owner_id: row
                    .try_get("owner_id")
                    .map_err(|e| ItemsError::Unavailable(e.to_string()))?,
                title: row
                    .try_get("title")
                    .map_err(|e| ItemsError::Unavailable(e.to_string()))?,
            })
        })
        .collect::<Result<Vec<_>, ItemsError>>()?;
    Ok(Json(json!({ "data": items })))
}

async fn admin_list_items(
    State(state): State<ItemsState>,
    Extension(principal): Extension<AdminPrincipal>,
) -> Result<Json<Value>, ItemsError> {
    require_scope(&principal, "items:read", ItemsError::Forbidden)?;
    let database = state
        .database
        .as_ref()
        .ok_or_else(|| ItemsError::Unavailable("database is not configured".into()))?;
    let rows = sqlx::query(
        "SELECT id, owner_id, title FROM items.items
         WHERE deleted_at IS NULL
         ORDER BY created_at DESC
         LIMIT 100",
    )
    .fetch_all(database.pool())
    .await
    .map_err(|error| ItemsError::Unavailable(error.to_string()))?;
    let items = rows
        .into_iter()
        .map(|row| {
            Ok(json!({
                "id": row.try_get::<Uuid, _>("id").map_err(|e| ItemsError::Unavailable(e.to_string()))?,
                "owner_id": row.try_get::<Uuid, _>("owner_id").map_err(|e| ItemsError::Unavailable(e.to_string()))?,
                "title": row.try_get::<String, _>("title").map_err(|e| ItemsError::Unavailable(e.to_string()))?,
            }))
        })
        .collect::<Result<Vec<_>, ItemsError>>()?;
    Ok(Json(json!({ "data": items })))
}

struct ItemCreatedLogger;

#[async_trait]
impl EventConsumer for ItemCreatedLogger {
    fn name(&self) -> &'static str {
        "items.item_created_logger"
    }

    fn topic(&self) -> &'static str {
        "items.item_created.v1"
    }

    async fn handle(&self, event: &EventEnvelope) -> Result<(), EventError> {
        tracing::info!(topic = %event.topic, id = %event.id, "items capability observed event");
        Ok(())
    }
}

struct ItemsHealth;

#[async_trait]
impl HealthCheck for ItemsHealth {
    async fn check(&self) -> HealthStatus {
        HealthStatus {
            component: "items".into(),
            healthy: true,
            message: None,
            latency_ms: 0,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn descriptor_is_stable() {
        let capability = ItemsCapability {
            state: ItemsState {
                database: None,
                auth: IdentityAuth::new(&AuthConfig {
                    issuer: "test".into(),
                    jwt_secret: "secret".into(),
                    ..AuthConfig::default()
                }),
                max_items: 10,
            },
        };
        assert_eq!(capability.descriptor().name, "items");
        assert_eq!(capability.scopes(), &["items:read"]);
    }
}
"#;

const ITEMS_MIGRATION: &str = r#"CREATE SCHEMA IF NOT EXISTS items;

CREATE TABLE IF NOT EXISTS items.items (
    id UUID PRIMARY KEY,
    owner_id UUID NOT NULL,
    title TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS items_owner_id_idx
    ON items.items (owner_id)
    WHERE deleted_at IS NULL;
"#;
